version: '3.8'

services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4 --timeout 300
    volumes:
      - ./recordings:/recordings
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - mongodb
    restart: always
    networks:
      - pige-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-pige}
      POSTGRES_USER: ${POSTGRES_USER:-pige}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - pige-network

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - pige-network
    volumes:
      - redisdata:/data

  mongodb:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-pige}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-pige}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-pige_audio}
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    restart: always
    networks:
      - pige-network

  worker:
    build: .
    command: celery -A config.celery_app worker --loglevel=info --concurrency=4
    volumes:
      - ./recordings:/recordings
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - mongodb
    restart: always
    networks:
      - pige-network

  beat:
    build: .
    command: celery -A config.celery_app beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - db
    restart: always
    networks:
      - pige-network

volumes:
  pgdata:
  redisdata:
  mongodata:

networks:
  pige-network:
    driver: bridge

